### ISSUE TITLE
User Interface for Betty

### ISSUE THREAD

**Issue by TRoskop** [pickhardt/betty#164]
Hello everybody!

As johnku1 (https://github.com/pickhardt/betty/issues/154) said betty might need a user interface I developed one.
You can see the results here:
![screenshot-1](https://cloud.githubusercontent.com/assets/13079737/9837013/5b6374ec-5a30-11e5-9ff6-739511236325.png)

*Here is the project:*  https://github.com/TRoskop/Betty-UI

**Comment by pickhardt** [comment]
Nice UI. If you want to be a maintainer of this project I could add you to the list. I don't actively maintain it currently.

**Comment by x-a-n-a-x** [comment]
See my https://github.com/pickhardt/betty/issues/154#issuecomment-140278633

**Comment by TRoskop** [comment]
First, thanks for the compliment.
Than, I think it is too bad that this good projects is not developed actively anymore.

About maintaining: Why not, so yes!

**Comment by pickhardt** [comment]
Would you be interested in actively working on it? This is a somewhat big commitment so think about it. I don't really have the time any longer to give it the attention it deserves.
