### ISSUE TITLE
Problem with command "whats my real name"

### ISSUE THREAD

**Issue by kvsjxd** [pickhardt/betty#182]
When I try to run the command `betty whats my real name` it says
`Betty: Running finger $(whoami) | sed 's/.*: *//;q'
sh: 1: finger: not found`
Please fix this command :)
![screenshot_20160826_183009](https://cloud.githubusercontent.com/assets/17274550/18006005/234a0ca4-6bbb-11e6-9417-d3c30cc76559.png)

**Comment by twrightsman** [comment]
@kvsjxd You don't have the finger command installed on your operating system. You need to install it first using your appropriate package manager.
