### ISSUE TITLE
Can anyone update this code?

### ISSUE THREAD

**Issue by StewAlexander-com** [pickhardt/betty#205]
@pickhardt or anyone -

Can we update or fork this? Fun tool, great as a virtual helper agent for Linux

Thanks in advance

**Comment by pickhardt** [comment]
I don't really look at this much but what pull request do you want? I can have a look and merge if it's simple.

**Comment by pickhardt** [comment]
If you have some ideas for what you want I could add you as a maintainer too.

**Comment by StewAlexander-com** [comment]
How about answering simple questions about the linux environment it is in as a start?

- "How big is is this directory" -- Betty does a recursive add of the file sizes within the directory tree and provides an answer
- "Is there / Do I have any empty directories / folders" -- does a lookup and lists them, with a caveat to any related to the kernel like "tmp" that should likely not be deleted
- Who logged in last? -- does lslogins or "w" or the like and provides the result in english, "user" last logged in "yesterday / today / date" at "time"
- What is my biggest directory / folder? - uses du or ncdu or something to figure out this, then betty replies "The [directory] under [directory path] is the biggest, it has "x" number of files, "y" being the largest"
- What files were last updated <in this directory / folder>? Betty replies with the files (say 5 files) with the most recent modification dates either system wide or in the directory requested
- What is using the network? -- req sudo output then dumps the output of "$lsof -i |grep -I established" 

A few suggestions -- betty could be a cool help tool for Linux, maybe

**Comment by pickhardt** [comment]
They sound cool. If you want to add them I can add you as a maintainer. I just don't really have the time to work on this these days.

**Comment by StewAlexander-com** [comment]
Hmm, not at the moment - but if I do I'll let you know

**Comment by StewAlexander-com** [comment]
@pickhardt  - closing this off for now, but I'll swing back around if I have some development free time.... betty could be best 😄
