### ISSUE TITLE
Provide option to configure Betty's name

### ISSUE THREAD

**Issue by coldhawaiian** [pickhardt/betty#27]
This is somewhat similar to [this issue](https://github.com/pickhardt/betty/issues/11). It would be extra cool if users could configure Betty to use a different name. For example, I might want to use "Alfred" (like from Batman), "Jarvis" (from Ironman), or "Watson " (from Sherlock Holmes), or to go extra geeky, "Computer" (like in Star Trek).

**Comment by christianoak** [comment]
I have an issue with this. Apparently you still need to call "betty" and ask for something, although the response is the name you changed: 
"betty change your name to Sirius
Sirius: OK. Call me Sirius from now on.
Sirius web on
bash: Sirius: command not found"

**Comment by pannous** [comment]
type `ln -s betty Sirius` in betty folder

**Comment by christianoak** [comment]
thank you :)
